### ISSUE TITLE
[Ask] I feel overheat in my browser

### ISSUE THREAD

**Issue by superdiazzz** [skewll/vue-vanta-revamp#1]
I love your works, thanks bro. but i just curious one thing. Does the library handle ondestroy state? I hope it would not overheat the browser

**Comment by skewll** [comment]
Hi, there is a way to destroy the component. I'll have to look into it. I am very new to this and am still learning Vue, Nuxt and CSS.

**Comment by skewll** [comment]
> I love your works, thanks bro. but i just curious one thing. Does the library handle ondestroy state? I hope it would not overheat the browser

I believe the answer lies someone in here, I will try to figure it out if I can find some time:
![Screenshot_20240305-110009_GitHub](https://github.com/skewll/vue-vanta-revamp/assets/73421224/935bde36-f0b1-4c42-8f5f-421c49a8452f)

**Comment by skewll** [comment]
> I love your works, thanks bro. but i just curious one thing. Does the library handle ondestroy state? I hope it would not overheat the browser

I believe I have a solution that will allow you to destroy update the instance from a page that is using the component. I will try to test it and get it published tomorrow. Right now, I can see it doesn't get destroyed automatically.

**Comment by skewll** [comment]
> I love your works, thanks bro. but i just curious one thing. Does the library handle ondestroy state? I hope it would not overheat the browser 
  
I believe I have a solution that will allow you to destroy and update the instance from a page that is using the component. That way you can have two options, keep it alive if you nav away and back is reuses current instance, or destroy onBeforeUnmount then reintialze instance when you nav back. 

I will try to test it and get it published tomorrow.  

Currently, I can see it doesn't get destroyed automatically when you nav away and then it creates another instance when you nav back.

**Comment by skewll** [comment]
> I love your works, thanks bro. but i just curious one thing. Does the library handle ondestroy state? I hope it would not overheat the browser 
  
I believe I have a solution that will allow you to destroy and update the instance from a page that is using the component. That way you can have two options, keep it alive if you nav away and back is reuses current instance, or destroy onBeforeUnmount then reintialze instance when you nav back. 

I will try to test it and get it published tomorrow.  

Currently, I can see it doesn't get destroyed automatically when you nav away and then it creates another instance when you nav back.

**Comment by skewll** [comment]
> I love your works, thanks bro. but i just curious one thing. Does the library handle ondestroy state? I hope it would not overheat the browser

Just published a new release. V0.1.2

Check out the Readme for new details.

Let me know if this fixed the issues you experienced.

I've added some features as well.
